/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.House;
import model.City;
import model.Community;
import model.CommunityHistory;

/**
 *
 * @author shobhitsrivastava
 */
public class CommunityPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalPanel
     */
    City city;
    CommunityHistory comHistory;
    static String userRole;

    public CommunityPanel(CommunityHistory comHistory, String userRole) {
        this.comHistory = comHistory;
        initComponents();
        this.userRole = userRole;
        validateUserRoles();
    }

    public void validateUserRoles() {
        if (userRole == "Community Admin") {
            System.out.println("the user role" + userRole);
            btnDeleteCommunity.setVisible(false);
        }

        if (userRole == "Patient") {
            btnDeleteCommunity.setVisible(false);
            btnUpdateCommunity.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        communityField = new javax.swing.JTextField();
        btnCreateCommunity = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        communityTableModel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cityFieldUpdate = new javax.swing.JTextField();
        communityFieldUpdate = new javax.swing.JTextField();
        btnUpdateCommunity = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnViewCommunity = new javax.swing.JButton();
        btnDeleteCommunity = new javax.swing.JButton();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("City Name");

        jLabel2.setText("Community Name");

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });
        cityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityFieldKeyPressed(evt);
            }
        });

        communityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityFieldActionPerformed(evt);
            }
        });
        communityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                communityFieldKeyPressed(evt);
            }
        });

        btnCreateCommunity.setText("CREATE");
        btnCreateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommunityActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("MANAGE COMMUNITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(communityField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(btnCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(communityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CREATE", jPanel1);

        communityTableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Community", "City"
            }
        ));
        jScrollPane1.setViewportView(communityTableModel);

        jLabel4.setText("City Name");

        jLabel5.setText("Community Name");

        cityFieldUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityFieldUpdateKeyPressed(evt);
            }
        });

        communityFieldUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                communityFieldUpdateKeyPressed(evt);
            }
        });

        btnUpdateCommunity.setText("UPDATE");
        btnUpdateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCommunityActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel7.setText("UPDATE");

        btnViewCommunity.setText("View");
        btnViewCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommunityActionPerformed(evt);
            }
        });

        btnDeleteCommunity.setText("Delete");
        btnDeleteCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDeleteCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(btnViewCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityFieldUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(communityFieldUpdate)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnUpdateCommunity)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cityFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(communityFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnUpdateCommunity)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );

        jTabbedPane1.addTab("VIEW", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommunityActionPerformed
        // TODO add your handling code here:
         boolean chckCity = false;
        boolean chckCommunity= false;
       

        chckCity = cityField.getText().isEmpty() ? true : false;
        chckCommunity = communityField.getText().isEmpty() ? true : false;


        if ((chckCity == false) && (chckCommunity == false)) {
        String community = communityField.getText();
        String city = cityField.getText();
        Community com = comHistory.addCommunity();
        com.setCommunityName(community);
        com.setCity(new City(city));
        JOptionPane.showMessageDialog(this, "Community Information Saved");
        }
    }//GEN-LAST:event_btnCreateCommunityActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        displayCommunity();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void cityFieldUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldUpdateActionPerformed

    private void btnUpdateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCommunityActionPerformed
        // TODO add your handling code here:
         boolean chckCity = false;
        boolean chckCommunity= false;
       

        chckCity = cityFieldUpdate.getText().isEmpty() ? true : false;
        chckCommunity = communityFieldUpdate.getText().isEmpty() ? true : false;


        if ((chckCity == false) && (chckCommunity == false)) {
        int selectedRowIndex = communityTableModel.getSelectedRow(); // Get the selected row index from the table
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the row to view");
            return;
        }
          try {
        DefaultTableModel model = (DefaultTableModel) communityTableModel.getModel();
        Community selectedCommunity = (Community) model.getValueAt(selectedRowIndex, 0);
        String community = communityFieldUpdate.getText();
        String city = cityFieldUpdate.getText();
        //String house = houseFieldUpdate.getText();
        selectedCommunity.setCommunityName(community);
        //selectedCommunity.setHouse(new House(house));
        selectedCommunity.setCity(new City(city));
        JOptionPane.showMessageDialog(this, "Community Information Updated");
        displayCommunity();
        }
          catch (Exception e) {
                System.out.println("Error" + e);
                JOptionPane.showMessageDialog(this, "Please provide correct values");
        }
        }
        
    }//GEN-LAST:event_btnUpdateCommunityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommunityActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = communityTableModel.getSelectedRow(); // Get the selected row index from the table
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) communityTableModel.getModel();
        Community selectedCommunity = (Community) model.getValueAt(selectedRowIndex, 0);
        communityFieldUpdate.setText(selectedCommunity.getCommunityName());
        cityFieldUpdate.setText(String.valueOf(selectedCommunity.getCity()));
        //houseFieldUpdate.setText(String.valueOf(selectedCommunity.getHouse()));
    }//GEN-LAST:event_btnViewCommunityActionPerformed

    private void btnDeleteCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCommunityActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = communityTableModel.getSelectedRow(); // Get the selected row index from the table
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) communityTableModel.getModel();
        Community selectedCommunity = (Community) model.getValueAt(selectedRowIndex, 0);
        comHistory.deleteCommunity(selectedCommunity);
        JOptionPane.showMessageDialog(this, "This record has been deleted");
        communityFieldUpdate.setText("");
        //houseFieldUpdate.setText("");
        cityFieldUpdate.setText("");
        displayCommunity();
    }//GEN-LAST:event_btnDeleteCommunityActionPerformed

    private void btnViewCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = communityTableModel.getSelectedRow(); // Get the selected row index from the table
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) communityTableModel.getModel();
        Community selectedCommunity = (Community) model.getValueAt(selectedRowIndex, 0);
        communityFieldUpdate.setText(selectedCommunity.getCommunityName());
        cityFieldUpdate.setText(String.valueOf(selectedCommunity.getCity()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void communityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityFieldActionPerformed

    private void cityFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityFieldKeyPressed
        // TODO add your handling code here:
           char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_cityFieldKeyPressed

    private void communityFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_communityFieldKeyPressed
        // TODO add your handling code here:
           char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_communityFieldKeyPressed

    private void cityFieldUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityFieldUpdateKeyPressed
        // TODO add your handling code here:
           char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_cityFieldUpdateKeyPressed

    private void communityFieldUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_communityFieldUpdateKeyPressed
        // TODO add your handling code here:
           char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_communityFieldUpdateKeyPressed

    private void displayCommunity() {
        System.out.println("Inside community");
        DefaultTableModel model = (DefaultTableModel) communityTableModel.getModel();
        model.setRowCount(0);
        for (Community em : comHistory.getCommunityHistory()) {
            System.out.println("commhistory" + em);
            Object[] row = new Object[3];
            row[0] = em;
            row[1] = em.getCity();
            model.addRow(row);

        }
//    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCommunity;
    private javax.swing.JButton btnDeleteCommunity;
    private javax.swing.JButton btnUpdateCommunity;
    private javax.swing.JButton btnViewCommunity;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField cityFieldUpdate;
    private javax.swing.JTextField communityField;
    private javax.swing.JTextField communityFieldUpdate;
    private javax.swing.JTable communityTableModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
